modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
[[mods]] #mandatory
# The modid of the mod
modId="magnificentmagicalmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Magnificent Magical Mod" #mandatory
credits="Inspiration from the Wizarding World, created by J.K. Rowling in her beloved Harry Potter series" #optional
authors="Exhanaver and Malachi Holden" #optional
#(#mandatory)
description='''
Magnificent Magical Mod
This mod incorporates into Minecraft various magical spells, potions, and world elements from the Wizarding World of Harry Potter
'''